apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.primary.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.primary.persistence.size }}
  storageClassName: {{ .Values.primary.persistence.storageClass }}
