apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-pvc
  labels:
    app: {{ include "chart.name" . }}
spec:
  accessModes:
    - {{ .Values.postgresql.primary.persistence.accessModes[0] }}
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size }}
  storageClassName: {{ .Values.postgresql.primary.persistence.storageClass | default "standard" }}
